default: &default
  shopify_client_api_key: <%= ENV['SHOPIFY_API_KEY'] %>
  shopify_client_api_secret: <%= ENV['SHOPIFY_SECRET_KEY'] %>
  shopify_client_redirect_uri: <%= ENV['SHOPIFY_REDIRECT_URI'] %>
  domain: <%= ENV['DOMAIN'] %>

development:
  <<: *default